### ISSUE TITLE
EDA Apps Visual organization (parent issue)

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1087]
This is the parent issue for main organization in the app-centric EDA.

See figma mockups for specifics.

To Dos

- [x] Select a visualization page. Break out new lines for each app (#1131 )
- [x] App configuration within full screen viz view (#1132 )
- [x] Viz thumbnail page - organization and vizs. Adds titles for each app type and parameter set (#1095 )
- [x] Viz thumbnail page - left navigation. VEuPathDB/web-eda#1121

**Comment by asizemore** [comment]
Closing parent issue since all tasks complete.
