### ISSUE TITLE
Subsetting: Tabular view and download for active variable

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#261]
### Subtasks

- [x] Investigate using a documented / widely supported data table library.
- [x] Determine how to display a full-screen modal in the EDA architecture.
- [x] Add property `dataTableSettings` which will hold information on which variables a user has selected for display in the data table as well as any sorting directives. 
- [x] Add a setter function called `setDataTableSettings` to the `AnalysisState`
- [x] Add an implementation of ⬆️ where needed.
- [x] Meet with Dave to determine remaining tasks and evaluate if some of them may be more efficiently handled by someone with more history all the components and custom hooks.
   - [X] How to determine the actual URL of the endpoint to call. Quick overview of API documentation.
   - [X] Does the existing variable tree component support multi-selection?
   - [x] Discuss how to make test calls to the API and the necessary authentication mechanisms.
   - [x] Identify components / custom hooks where additional context is needed.
- [x] Add the necessary method to the DataClient (not sure if this the correct name) to access the temporary API endpoint.
- [x] Create a new multi-select variable tree component which will allow for a user to select more than one variable at a time.
- [x] Make a download utility to download the table. This will likely use the same backend service endpoint as the table, but with a different format, and with all rows.
- [x] Use data restriction utilities to protect access to the table/paging/download functionality. Work with @dmfalke or @jtlong3rd on this.  
- [x] Utilize backend analysis store.
- [x] Make the variable selector overlay the table rather than truncating it. There may be different ways of doing this, but consider using the `VariableTreeDropdown` component first.
- [x] Make the style of the table more consistent with legacy Mesa tables.
- [x] Make the buttons more consistent with existing EDA buttons.
- [x] Add paging support.
- [x] Save current paging data to Analysis state so that it will reload appropriately when the user closes/re-opens the modal.
- [x] Add filtering support.

The table/download can use the [table viz endpoint](https://veupathdb.github.io/EdaDataService/api.html#resources:/apps/pass/visualizations/table:post) for now. It will be replaced with something more performant soon, but with the same API.. We will likely want to use the [Mesa](https://github.com/VEuPathDB/WDKClient/tree/master/Client/src/Components/Mesa) React component for this.

### UX Requirements

These are the latest requirements from the EDA Workspace UX Meeting:

- [x] If the entity has an featured or starred variables, use those as defaults if the user hasn't picked any.
- [x] If the entity has no featured/starred variables and the use hasn't picked any, display "getting started" instructions.
- [x] Show IDs (including ancestral / parent entity ids)
- [x] Have quick way to add current variable users are looking at
- [x] Once a user picks their own variables for the table, that would become the default view when they open the table again. In other words, load previous selections from analysis state.
- [x] Include paging support.
- [x] Propose to not include starred variables in the table by default since those can be changed and the whole point of the starring is to make it easy to pick them for things like this table
- [x] Alert users to out of memory errors when they select too many columns.

**Comment by dmfalke** [comment]
I think when this view is active, the route should be updated to look something like this:

```
/:studyId/:analysisId/variables/:entityId/download
```

A part of the requirements is to include a "quick link" to add the variable that the user was looking at, as a column to the table. I think we can pass that bit of state to this view using history state. If we do that, then the button we currently have would need to be turned into a `<Link>` from `react-router-dom`, which allows you to pass in history state.

Let me know what you think, @eikonomega.

**Comment by eikonomega** [comment]
Will utilize two components from the new `core-components` package. 
* `FullScreenModal` and `DataGrid`.
* DataGrid in particular, is built off of the well documented https://react-table.tanstack.com/ library and as a strong candidate for replacing Mesa tables.

**Comment by eikonomega** [comment]
@dmfalke ```Make a download utility to download the table. This will likely use the same backend service endpoint as the table, but with a different format, and with all rows.```

Wouldn't this be some sort of API endpoint that would return a CSV file?

**Comment by eikonomega** [comment]
@dmfalke Working on the variable selection right now.

![image](https://user-images.githubusercontent.com/415939/131914808-fff15a5d-c273-4e8a-82a6-754761d25dce.png)

Given the data model we setup yesterday, a user can only select a single entity at a time and then any number of the child variables associated with that entity.

I'm not sure having the "Featured Variables" for the column selector makes sense in light of this. We can discuss tomorrow.

**Comment by danicahelb** [comment]
Hi Mike! I checked in with the clinepi team and we will be fine with a table preview with just 20 rows of data. We don’t need you to implement histograms by clicking on the column headers of the data since we can easily create these in the visualize tab of the EDA. let me know if you have questions!

**Comment by danicahelb** [comment]
Discussed on a slack call with @eikonomega @steve-fischer-200 @dmfalke @SheenaTomko and @danicahelb 

**Background**: 

Mike had previously asked the question if paging/downloading unknown number of records was necessary if the purpose of the modal was just to select columns and then download since I understood that to be the primary purpose of the view. If the view is both for this purpose and for general exploration of the data in a tabular format, then of course we will have to implement paging. This extra work would just be unnecessary if exploration of the data was not a purpose of the view.

Here are the extra items that will need to be addressed to support server-side paging. (Mike estimated that this will take ~2 days since he doesn't know how complex #2 will be off-hand).

1. Need to keep track of paging “state” in the analysis object itself.
2. Need to update the DataGrid component to support server-side paging. Currently it only supports client side paging where all the data is loaded at one.

**Use cases for the subset results table:** Preview the download file, so that:

1. Users can see that each column represent a unique variable & rows represent unique participants / households / samples / observations, etc (which is very different than the tree view offered on the site)
2. Users can verify that the variables they have included in the table are the ones they are interested in. Many variables have similar display labels, so it helps to actually see values for each variable

Since it doesn't seem to be too much additional work to offer paging of the subset results table, it was decided to offer it. **Reasons to support paging:**

1. If by chance the 20 rows of data include only NAs (which is certainly possible), the user won't be able to see the structure of the variables selected & will have a difficult time knowing that data will actually be in the download file.
2. ClinEpiDB can add pre-drawn complex per-participant level graphics into the subset results table (like the longitudinal Z-score summary graphics available for MAL-ED participants on the live site.

**Comment by danicahelb** [comment]
Discussed in 10/4 EDA WG meeting:

**Columns:**
- Results table will be populated with all featured and starred variables as default columns
- If an entity has no featured or starred variables, there will be no default table view. Instead, users will see text instructing them on how to make the table:
- [ ] Update verbiage: To get started, click on the “Selected variables” button
- [ ] Styling updates to make it clear that the user needs to click the button: (i) Make text bigger, (ii) Move text up a bit & center, (iii) Hyperlink “Selected variables”
- Column selections get saved within an analysis, so if you close and open the results table, your column selections will still be there
- Do **NOT**: (i) Add a column for the last variable the user was looking at or (ii) Have the variable tree open by default if there are no featured or starred variables for that entity

**Enhancements in development:**

- [ ] Variable tree updates:
- Move all check-boxes to the left, following the indentation pattern for parents & children
- Align all stars on the right

- [ ] Data access restrictions: Dave, Jamie, and Mike to work together on this
- Limited paging
- Seeing >20 rows of data
- Downloading

- [ ] Column sorting

- [ ] Title/header for the modal: 
- Study name & name of the analysis should be formatted identically to how they are on the analysis page (same font, text, size)
- Clearly & prominently indicate entity space, # in subset, and # in dataset (see text in the relevant box in the entity diagram)

**Bug:** If you apply a filter, the number of pages changes but the data you have filtered out is still in the table
- Ex: PRISM2, filter by sex = male
- Number of pages in the results table drops from ~54 to ~26
- However, you still see rows for females in the table!

**Comment by danicahelb** [comment]
@eikonomega I'm going to move this to phase 2 to make sure it gets properly QA'd, so don't stress about getting this done in the next 2 days. We should be on track for this to go out in b55.

**Comment by danicahelb** [comment]
discussed in 10/18 EDA WG meeting: changes requested

- [ ] Have the variable tree open (expanded) within the variable picker box by default

- [ ] Close button: change to an “X” and move to the top of the View subset table modal (so it is clear that the “X” closes the modal and not the variable picker)

- [ ] Add a minimize icon (“_”) to the variable picker box (move the contents of the box down to make room for the minimize icon)

**Comment by bobular** [comment]
Reopen pending uncommenting of button

**Comment by danicahelb** [comment]
subset results table is currently hidden, so I'm adding a pause

**Comment by danicahelb** [comment]
Closing this ticket as all issues are now being tracked in https://github.com/VEuPathDB/web-eda/issues/656
