### ISSUE TITLE
Scatterplot: add gradient colormap for continuous overlay variables

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#306]
------------------
***NOTE: This is now a duplicate of https://github.com/VEuPathDB/web-eda/issues/1399***
------------------

## Tasks

- [x] Pick sequential gradient map. Decided on the darkest 90% of colors from [oslo colormap](https://www.fabiocrameri.ch/colourmaps/). 
- [x] Gradient colormap legend.
- [x] Handle how no data interacts with gradient colormap. Plan: put the No Data in it's own, non-clickable, slot in the legend. Add prop to send hasMissingData to colormap legend and it can handle adding a no data line.
- [x] plot.data handle missing data. Needs to return a new seriesGradientColormap named "no data" or similar.
- [x] data service updates. 
- [x] web-eda general implementation
- [x] web-eda gradient colorscale turns off trendlines
- [x] Use annotated displayRangeMin and max if given (look at `defaultDependentAxisRange`). If not given, use rangeMin and rangeMax.
- [x] web-eda handle the dual overlay var constraints.

## Associated PRs
- web-components [#275](https://github.com/VEuPathDB/web-components/pull/275)
- plot.data [PR 124](https://github.com/VEuPathDB/plot.data/pull/124)
- web-eda [PR #790](https://github.com/VEuPathDB/web-eda/pull/790)
- data service [PR #138](https://github.com/VEuPathDB/EdaDataService/pull/138)

## Open questions

- [ ] Markers? Filled circles?
- [ ] Pick diverging map. IP
- [ ] How to handle "discrete" vars? If we let integers with < 9 unique values in, do they get categorical, gradient, or discrete? 
- [ ] Var constraints more generally. Right now set up to use var info to determine how the viz runs (web-eda). Are we happy sending all numeric (for example) vars to go through series gradient colormap? If var has values = 1:7, they could still get a seriesGradientColormap but then when sent to the legend are legend-ized appropriately.

## To Dos for later cards

- [ ] Allow dates
- [ ] Add controls for user to select colormap, range, midpoint (maybe future phase?)

**Comment by danicahelb** [comment]
This does not work for ClinEpi

**I cannot select a continuous overlay variable**


![Image](https://user-images.githubusercontent.com/25450900/202043478-baa86b99-7522-4a59-a376-b0f19b19ecbc.png)

**When I choose a categorical overlay variable with numeric values I (incorrectly) get the gradient legend but the colors don't match what is being plotted**


![Image](https://user-images.githubusercontent.com/25450900/202043606-0f982b8a-9448-4853-bf03-7e7be9034afc.png)



Also, may be related to https://github.com/VEuPathDB/web-eda/issues/1481

**Comment by danicahelb** [comment]
I'm marking this as complete as it duplicates #1399
