### ISSUE TITLE
Visualizations: Enable first iterate of faceting

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#635]
The following features comprise the first iterate of faceting:

1. One facet var - always column facet
3. Max var values allowed is 8
4. Thumbnail image shows 2 panels
5. No data always plotted in the last column
6. Fullscreen/enlarging one panel (extra - could be dropped if time does not allow)

There is a **web-components** [component](https://github.com/VEuPathDB/web-components/pull/162) to this feature, which is already under development.

Subtasks

- [x] merge https://github.com/VEuPathDB/web-components/pull/162
- [x] finish wiring/sorting (solves 4.) for all visualizations https://github.com/VEuPathDB/web-eda/pull/640 , #658, #659, #660
- [x] fully implement FacetedPlot https://github.com/VEuPathDB/web-components/issues/240
- [x] thumbnail image capture https://github.com/VEuPathDB/web-components/issues/241 
- [x] custom legend https://github.com/VEuPathDB/web-components/pull/237
- [x] placement/layout of legend/side plots/controls for faceted and unfaceted plots in EDA https://github.com/VEuPathDB/web-eda/issues/648
- [x] y-axis scaling for Boxplot https://github.com/VEuPathDB/web-eda/issues/650
- [x] handle empty facets appropriately - wiring done, just finalising some styling here: https://github.com/VEuPathDB/web-components/pull/262 
- [x] finalise mosaic layout #725 

ETA: here is a mock-up
![image](https://user-images.githubusercontent.com/365139/138996609-b2f34520-0504-4d12-971a-987d8dda9aed.png)

**Comment by dmfalke** [comment]
@jtlong3rd has agreed to work on the thumbnail and layout issues.

**Comment by bobular** [comment]
Closing manually.  All subtasks done :tada:

**Comment by SheenaTomko** [comment]
Moving to complete. Steph is still qa'ing https://github.com/VEuPathDB/web-eda/issues/648, but that can be reopened or a new ticket made if needed
