### ISSUE TITLE
Implement UI component for site search

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#920]
Implement the UI component for the site search, as defined in mockups indicated in https://github.com/VEuPathDB/EdaNewIssues/issues/173 

See site search parent task here: https://redmine.apidb.org/issues/41968

### TODOs

- [x] Enable site search user interface
- [x] Add search box to header
- [x] Add custom rendering for new document types (Study, Variable, VariableValue), including summary tables.

**Comment by steve-fischer-200** [comment]
i put this in web-eda, but i guess its not the right home.  seems we want a common home for eda and website site search ui?

**Comment by nkittur-uga** [comment]
UI components are in place. QA is complete.
